### PR TITLE
Fix/Refactor language support

### PR DESCRIPTION
**Pull request by Ecconia**
The previous language support code has a long history in code and in bugs.
This refactor attempts to get rid of all remaining bugs and clean up the code to make it more readable.

Old issues:
- Crash when unsupported system language. (Already fixed on here)
- On orientation change, it switches to English.
- When language was fixed, it causes a loop on orientation change.
- One activity never bothered to restart (check for language changes).

The LanguageSetting class has been removed and the enum LanguageCode became its own file.
There is no need to store system and language code together in an activity. That only adds complexity and weird cases.
Now EACH activity stores its language code and checks whenever it gets opened/turned if the locale is still correct.

onConfigurationChange never seemed to be called. Its purpose was not obvious to me either. I removed all which had been added for language.

### CODE REVIEW

**Comment by Ecconia** [comment]
Disclaimer: I still am new to Kotlin. There might be unforseen side effects. I primary just used the built-in converting tool. The original code was written in Java: <https://github.com/Ecconia/SudoQ/commit/0d0c1b18f2872e190c50d39b26dbf8e20a5e6a19>

Also my knowledge about Android might not be good in edge cases and version support. Hence please confirm my approach.

There are two/three things to think about in this PR:
- Previously the language code only applied on some activities, the ones which one could go back to. However one got forgotten. Now the language checking code is applied to all activities. (Minor overhead in some).
- I am no longer using onConfigurationChanged() for language, was that ever triggered? It "should" work without it just well (for me at least). [Tested on Android 9].
- I got rid of the LanguageSetting, that makes the code significantly more easy and nice to look at. Now there are only three places where "logic" is applied.
- The initial setting of the resource locale now happens in the splash-screen instead of the main-menu. (But it can happen in any activity, since the new code confirms that its valid).

All the bugs disappeared for me. I found new unrelated bugs though :) But from the Kotlin conversion.

Please let me know what you think about this approach. I will gladly adjust whatever is lacking.

**Comment by timo-a** [comment]
Hi, thank you for your contribution!
I just tried it out and when I go to `New Sudoku` -> `Adjust Assistances` -> `Advanced Settings` and change the language from `system` to e.g. french and navigate back via the `back` button I have to press twice to get out of `NewSudokuPreferencesActivity` and `NewSudokuActivity` each. Can you please fix that?

**Comment by Ecconia** [comment]
Now this is interesting. I had this bug when I worked on this code. But I moved the `finish()` call before the `startActivity()` call to fix this issue. Since then the bug disappeared for me. And I cannot reproduce it, using the steps you described.

Which Android version are you using? Which system language?
(For me that is Version 9 and my system language is English).

Maybe please also have a look at the debugging output of the application.
There is a prefix `SudoQLanguage` which prints a message, whenever an activity restarts due to language changes.
For me each activity (on the history stack) prints one message, as it should. (Starting from the AdvancedPreferencesActivity, down to the `MainActivity`).

**Comment by Ecconia** [comment]
I started an emulator and was able to see the symptoms with Android 5.1
So I can reproduce it now. Will fix it, given I do eventually understand Android activity history properly :P

**Comment by Ecconia** [comment]
Hmm, this commit works. But I the documentation of these two flags does not exactly match what we need here.
Maybe there is a better solution.

**Comment by Ecconia** [comment]
I changed the commit to only use `CLEAR_TOP` since its functionality is sufficient.
Please confirm that this fix works for you.

**Comment by timo-a** [comment]
I confirm, this works for me (Android 8)

**Comment by Ecconia** [comment]
-> I just noticed that the merge squish commit, did not contain the issue description that I wrote.

I am trying to always put a proper description into my commits.
Cause then other people who read these commits know:
- Why was the commit made.
- What does it improve.
- How does it improve it.
- Are there side effects?
(Given this information is not obvious from the source code.)

Describing things like these and separating unrelated changes into different commits are very important things to do, to keep a git repository clean and easy for others to understand. Which leads to further good contributions.

---

Is there a specific reason, that you are using squish instead of merge commits for all PRs?
(I am asking, because with for example merge commits, the description is not that important.)

(Following is my opinion/perception, with my current state of experience:)
Squish commits are okay for small branches like this one - given the description is properly, and only one topic is tackled.
But for example your Kotlin refactoring just gives me a chunk of question-marks, and I have to look at GitHub to understand which process you made while refactoring this project. A merge commit would have made this process easier for me.

---

I really like this application and I think there are only a few features missing to make it the best Sudoku application out there. (Have a looks at the Microsoft Sudoku app, it has a few awesome features).

So on my way to make this application better, I am confronted with bugs.
And it is my token of appreciation to also fix them on this fork.
So that others also have a great time enjoying this application.

But I also want this repository to look good, at least the parts that I worked on.
So I did add some nice descriptions so far (imo). However this time, the squish commit description was missing.
Now other possible contributors and our future self have to look at this PR on GitHub to know why the language code was refactored.

I do not know if GitHub did not provide a pre-created description this time. Or if it was removed by an accident or if the description was actively removed. Issue is, the description is missing.

---

Now this section might sound a bit much salty. Because of language and because I am a little bit unhappy about this.

Nobody should tell anyone, how they should manage their git repository (I guess and sorry). This is totally up to the maintainer.

But please take care of the commits I am involved with, as much as I would do (in this case, a good commit description).
Cause I would like to continue working with you on this project. (Given that is fine for you.)
To make this application and its git repository even more awesome in future.

**Comment by timo-a** [comment]
> Is there a specific reason, that you are using squish instead of merge commits for all PRs?

- I find merges messy (I'm working on myself :smiley:) and hard to undo, or diff because then there are two paths where a change can come from   
- case in point: I already had to merge master into your PR after I merged your last PR on master, squish seemed more straight forward 
- In my experience detailed commit messages are helpful for the reviewer but not needed after the merge, as all relevant information goes into the code.
- The same goes for commits. I like doing micro commits while I work on a new feature but after everything works, I don't need them anymore.

So from my point of view squishing was simpler with no downsides.

> I do not know if GitHub did not provide a pre-created description this time. Or if it was removed by an accident or if the description was actively removed.

Github prefilled all the commit messages in the squish. Since I'm not used to contributions, I got used to putting one line summaries on the master branch myself and deleted everything after the first line without giving it any thought. I try to use Gitflow for this project (which I haven't put in the Readme yet because until recently there were no contributions) and to my understanding only high level descriptions of the changes should be on the master branch there.
But I am happy to (reasonably :smiley:) cater to contributors needs if I know about them  -> thank you for communicating. 
I have amended the squish commit of this PR so it has the information the untouched `squish and merge` commit would have had and will merge future PRs from you via merge commit. By the way only `squish and merge` seems auto fill all commit messages of the PR, in `create a merge commit` I have to write my own commit, so I would just copy all commit messages from `squish and merge`, and paste them into a `create a merge commit`. If there are several commit messages, I'll preface them with a short summary that I write myself. You are of course welcome to provide your own via a comment on the PR.

**Comment by Ecconia** [comment]
Okay sounds good!
Keeping big refactoring actions simple to understand is indeed major difficult and takes a lot of planning and tinkering and time. (So I can tell, that often it is not worth it).

I will also consider this, when contributing from now on!
And if the change requires it, I will provide a suggested squish-merge commit message, sounds like the most easy solution for my issue :)

Very late reply, I just got back to Sudoku-programming.

**Pull request merged**
